name: Daily Cypress Test

on:
  schedule:
    - cron: '15 8 * * *' 
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: self-hosted


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Send Telegram Alert if Cypress fails
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="🚨 *Cypress Test Failed* in MYN143 Dashboard!" \
          -d parse_mode=Markdown

          
